version: '3'
services:  

  db:
    image: ${DB_IMAGE}
    container_name: ${DB_NAME}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DB}

  rabbit: 
    image: ${RABBIT_IMAGE}
    container_name: ${RABBIT_NAME}
    ports: 
      - ${RABBIT_PORT}:15672 
  
  web:
    build:
      context: .
      dockerfile: Dockerfile_Django
    image: ${APP_IMAGE}
    container_name: ${APP_NAME}
    command: ${APP_RUN}
    depends_on:
      - db
    volumes:
      - ./static:/root/collected_static 

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image : ${NGINX_IMAGE}
    container_name: ${NGINX_NAME}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./static:/var/www/static
    depends_on:
      - web
  
  worker:
    image: ${APP_IMAGE}
    container_name: ${CELERY_WORKER}
    command: ${CELERY_WORKER_RUN}
    depends_on:
      - rabbit
      - web
  beat:
    image: ${APP_IMAGE}
    container_name: ${CELERY_BEAT}
    command: ${CELERY_BEAT_RUN}
    depends_on:
      - rabbit
      - web
